generated_data_path: "/home/nikifori/Desktop/anomaly_detection/generated_data_v2"

methods:
  - "IForest"
  - "SAND"
  - "SAND"
  - "HBOS"
  - "IForest"
  - "IForest"
  - "IForest"
  - "HBOS"
  - "HBOS"
  - "HBOS"
  - "MatrixProfile"
  - "MatrixProfile"
  - "MatrixProfile"
  - "IForest"
  - "HBOS"

num_of_normalities_under_test: [ 1, 2, 3 ] # [ 1, 2, 3, 4, 5 ]
# num_of_normalities_under_test: [ 1 ] # [ 1, 2, 3, 4, 5 ]

normalities_under_test:
  - "Dodgers"
  - "ECG"
  - "SVDB"

# ["offline", "online"]
type:
  - "offline"
  - "offline"
  - "online"
  - "offline"
  - "online"
  - "online"
  - "online"
  - "online"
  - "online"
  - "online"
  - "offline"
  - "online"
  - "online"
  - "online"
  - "online"

online_variant:
  - null
  - null
  - null
  - null
  - "naive"
  - "movingAverage"
  - "precedingHistory"
  - "naive"
  - "movingAverage"
  - "precedingHistory"
  - null
  - "naive"
  - "precedingHistory"
  - "adaptiveDecay"
  - "adaptiveDecay"

# exp_name: "testing"
exp_name: "exp_08_06_2025"

output_dir: "/home/nikifori/Desktop/anomaly_detection/eval/"

cpu_num: 1

save_plots: true